

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 399)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(250, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(440, 20, 161, 221))
        self.groupBox.setObjectName("groupBox")
        self.spinLocators = QtWidgets.QPushButton(self.groupBox)
        self.spinLocators.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.spinLocators.setObjectName("spinLocators")
        self.armLocators = QtWidgets.QPushButton(self.groupBox)
        self.armLocators.setGeometry(QtCore.QRect(10, 60, 121, 23))
        self.armLocators.setObjectName("armLocators")
        self.legLocators = QtWidgets.QPushButton(self.groupBox)
        self.legLocators.setGeometry(QtCore.QRect(10, 90, 121, 23))
        self.legLocators.setObjectName("legLocators")
        self.footPivots = QtWidgets.QPushButton(self.groupBox)
        self.footPivots.setGeometry(QtCore.QRect(10, 120, 121, 23))
        self.footPivots.setObjectName("footPivots")
        self.handLocators = QtWidgets.QPushButton(self.groupBox)
        self.handLocators.setGeometry(QtCore.QRect(10, 150, 121, 23))
        self.handLocators.setObjectName("handLocators")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 190, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(440, 290, 151, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 260, 181, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, -10, 191, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(50, 60, 104, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 171, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.functionsAutorig = QtWidgets.QPushButton(Dialog)
        self.functionsAutorig.setGeometry(QtCore.QRect(30, 20, 191, 23))
        self.functionsAutorig.setObjectName("functionsAutorig")
        self.spineAutorig = QtWidgets.QPushButton(Dialog)
        self.spineAutorig.setGeometry(QtCore.QRect(30, 60, 191, 23))
        self.spineAutorig.setObjectName("spineAutorig")
        self.armAutorig = QtWidgets.QPushButton(Dialog)
        self.armAutorig.setGeometry(QtCore.QRect(30, 110, 191, 23))
        self.armAutorig.setObjectName("armAutorig")
        self.legAutorig = QtWidgets.QPushButton(Dialog)
        self.legAutorig.setGeometry(QtCore.QRect(30, 170, 191, 23))
        self.legAutorig.setObjectName("legAutorig")
        self.handAutorig = QtWidgets.QPushButton(Dialog)
        self.handAutorig.setGeometry(QtCore.QRect(30, 220, 191, 23))
        self.handAutorig.setObjectName("handAutorig")
        self.spineNumber = QtWidgets.QSpinBox(Dialog)
        self.spineNumber.setGeometry(QtCore.QRect(240, 60, 42, 22))
        self.spineNumber.setMinimum(1)
        self.spineNumber.setProperty("value", 5)
        self.spineNumber.setObjectName("spineNumber")
        self.upperArmNumber = QtWidgets.QSpinBox(Dialog)
        self.upperArmNumber.setGeometry(QtCore.QRect(240, 110, 42, 22))
        self.upperArmNumber.setMinimum(1)
        self.upperArmNumber.setProperty("value", 5)
        self.upperArmNumber.setObjectName("upperArmNumber")
        self.lowerArm = QtWidgets.QSpinBox(Dialog)
        self.lowerArm.setGeometry(QtCore.QRect(320, 110, 42, 22))
        self.lowerArm.setMinimum(1)
        self.lowerArm.setProperty("value", 5)
        self.lowerArm.setObjectName("lowerArm")
        self.upperArm = QtWidgets.QSpinBox(Dialog)
        self.upperArm.setGeometry(QtCore.QRect(240, 170, 42, 22))
        self.upperArm.setMinimum(1)
        self.upperArm.setProperty("value", 5)
        self.upperArm.setObjectName("upperArm")
        self.lowerLeg = QtWidgets.QSpinBox(Dialog)
        self.lowerLeg.setGeometry(QtCore.QRect(320, 170, 42, 22))
        self.lowerLeg.setMinimum(1)
        self.lowerLeg.setProperty("value", 5)
        self.lowerLeg.setObjectName("lowerLeg")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 40, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(240, 90, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(320, 90, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(240, 150, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(320, 150, 61, 16))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Generate Locators", None, -1))
        self.spinLocators.setText(QtWidgets.QApplication.translate("Dialog", "Spine locators", None, -1))
        self.armLocators.setText(QtWidgets.QApplication.translate("Dialog", "Arm Locators", None, -1))
        self.legLocators.setText(QtWidgets.QApplication.translate("Dialog", "Leg locators", None, -1))
        self.footPivots.setText(QtWidgets.QApplication.translate("Dialog", "Foot pivots", None, -1))
        self.handLocators.setText(QtWidgets.QApplication.translate("Dialog", "Hand locators", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("Dialog", "RadioButton", None, -1))
        self.plainTextEdit.setPlainText(QtWidgets.QApplication.translate("Dialog", "Ejecutar primero las funciones para poder ejecutar el resto del autorig", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Nomenclatura - Huesos", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Predefinida:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "partNumber_side_function", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Prefix:                                      _", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("Dialog", "Alterate", None, -1))
        self.functionsAutorig.setText(QtWidgets.QApplication.translate("Dialog", "Functions!!", None, -1))
        self.spineAutorig.setText(QtWidgets.QApplication.translate("Dialog", "Spine AutoRig", None, -1))
        self.armAutorig.setText(QtWidgets.QApplication.translate("Dialog", "Arm Autorig", None, -1))
        self.legAutorig.setText(QtWidgets.QApplication.translate("Dialog", "Leg Autorig", None, -1))
        self.handAutorig.setText(QtWidgets.QApplication.translate("Dialog", "Hand Autorig", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Spine Jnts", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "upArm Jnts", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "lowArm Jnts", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "upLeg Jnts", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "lowLeg Jnts", None, -1))

